server:
  port: 8080

spring:
  application:
    name: chatbot-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/chatbot_db}
    username: ${SPRING_DATASOURCE_USERNAME:chatbot_user}
    password: ${SPRING_DATASOURCE_PASSWORD:chatbot_password}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
  jackson:
    serialization:
      INDENT_OUTPUT: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  health:
    db:
      enabled: true

openai:
  base-url: "https://api.openai.com/v1"
  api-key: "${OPENAI_API_KEY:}"
  model: "gpt-4o-mini"

logging:
  level:
    root: INFO
    com.pidima.chatbot: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
